package team.maverick.code.girish.entity.old;

import javax.persistence.Column;
import javax.persistence.Embeddable;

// Generated 29 Apr, 2018 4:20:19 PM by Hibernate Tools 5.2.3.Final

/**
 * CarPoolBookingId generated by hbm2java
 */
@Embeddable
public class CarPoolBookingId implements java.io.Serializable {

	@Column(name="seeker_id")
	private String seekerId;
	
	@Column(name="slot_id")
	private int slotId;

	public CarPoolBookingId() {
	}

	public CarPoolBookingId(String seekerId, int slotId) {
		this.seekerId = seekerId;
		this.slotId = slotId;
	}

	public String getSeekerId() {
		return this.seekerId;
	}

	public void setSeekerId(String seekerId) {
		this.seekerId = seekerId;
	}

	public int getSlotId() {
		return this.slotId;
	}

	public void setSlotId(int slotId) {
		this.slotId = slotId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CarPoolBookingId))
			return false;
		CarPoolBookingId castOther = (CarPoolBookingId) other;

		return ((this.getSeekerId() == castOther.getSeekerId()) || (this.getSeekerId() != null
				&& castOther.getSeekerId() != null && this.getSeekerId().equals(castOther.getSeekerId())))
				&& (this.getSlotId() == castOther.getSlotId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSeekerId() == null ? 0 : this.getSeekerId().hashCode());
		result = 37 * result + this.getSlotId();
		return result;
	}

}
