package team.maverick.code.girish.entity.old;
// Generated 29 Apr, 2018 4:20:19 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Destination generated by hbm2java
 */
@Entity
@Table(name="destination")
public class Destination implements java.io.Serializable {

	@Column(name="destination_id")
	@Id
	private int destinationId;
	
	@Column(name="destination_name")
	private String destinationName;
	
	@Column(name="area")
	private String area;
	
	@OneToMany(fetch=FetchType.LAZY, mappedBy="destination", targetEntity=CarPoolSlot.class)
	private Set carPoolSlots = new HashSet(0);

	public Destination() {
	}

	public Destination(int destinationId) {
		this.destinationId = destinationId;
	}

	public Destination(int destinationId, String destinationName, String area, Set carPoolSlots) {
		this.destinationId = destinationId;
		this.destinationName = destinationName;
		this.area = area;
		this.carPoolSlots = carPoolSlots;
	}

	public int getDestinationId() {
		return this.destinationId;
	}

	public void setDestinationId(int destinationId) {
		this.destinationId = destinationId;
	}

	public String getDestinationName() {
		return this.destinationName;
	}

	public void setDestinationName(String destinationName) {
		this.destinationName = destinationName;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public Set getCarPoolSlots() {
		return this.carPoolSlots;
	}

	public void setCarPoolSlots(Set carPoolSlots) {
		this.carPoolSlots = carPoolSlots;
	}

}
