package team.maverick.code.girish.entity;
// Generated 29 Apr, 2018 4:20:19 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * CarPoolBooking generated by hbm2java
 */
@Entity
@Table(name="car_pool_booking")
public class CarPoolBooking implements java.io.Serializable {

	@EmbeddedId
	 @AttributeOverrides( {
	      @AttributeOverride(name = "slotId", column = @Column(name = "slot_id"))
	       })
	private CarPoolBookingId id;
	
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "slot_id" , referencedColumnName = "slot_id",insertable = false, updatable=false)
	private CarPoolSlot carPoolSlot;
	
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "seeker_id" , referencedColumnName = "user_id",insertable = false, updatable=false)
	private UserDetail userDetail;
	
	@Column(name="last_update_time")
	private Date lastUpdateTime;

	public CarPoolBooking() {
	}

	public CarPoolBooking(CarPoolBookingId id, CarPoolSlot carPoolSlot, UserDetail userDetail) {
		this.id = id;
		this.carPoolSlot = carPoolSlot;
		this.userDetail = userDetail;
	}

	public CarPoolBooking(CarPoolBookingId id, CarPoolSlot carPoolSlot, UserDetail userDetail, Date lastUpdateTime) {
		this.id = id;
		this.carPoolSlot = carPoolSlot;
		this.userDetail = userDetail;
		this.lastUpdateTime = lastUpdateTime;
	}

	public CarPoolBookingId getId() {
		return this.id;
	}

	public void setId(CarPoolBookingId id) {
		this.id = id;
	}

	public CarPoolSlot getCarPoolSlot() {
		return this.carPoolSlot;
	}

	public void setCarPoolSlot(CarPoolSlot carPoolSlot) {
		this.carPoolSlot = carPoolSlot;
	}

	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

}
