package team.maverick.code.girish.entity;
// Generated 29 Apr, 2018 4:20:19 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CarPoolBooking generated by hbm2java
 */
@Entity
@Table(name="car_pool_booking")
public class CarPoolBooking implements java.io.Serializable {

	@Id
	private CarPoolBookingId id;
	
	private CarPoolSlot carPoolSlot;
	private UserDetail userDetail;
	private Date lastUpdateTime;

	public CarPoolBooking() {
	}

	public CarPoolBooking(CarPoolBookingId id, CarPoolSlot carPoolSlot, UserDetail userDetail) {
		this.id = id;
		this.carPoolSlot = carPoolSlot;
		this.userDetail = userDetail;
	}

	public CarPoolBooking(CarPoolBookingId id, CarPoolSlot carPoolSlot, UserDetail userDetail, Date lastUpdateTime) {
		this.id = id;
		this.carPoolSlot = carPoolSlot;
		this.userDetail = userDetail;
		this.lastUpdateTime = lastUpdateTime;
	}

	public CarPoolBookingId getId() {
		return this.id;
	}

	public void setId(CarPoolBookingId id) {
		this.id = id;
	}

	public CarPoolSlot getCarPoolSlot() {
		return this.carPoolSlot;
	}

	public void setCarPoolSlot(CarPoolSlot carPoolSlot) {
		this.carPoolSlot = carPoolSlot;
	}

	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

}
